{
 "title": "MLE_monitoring_real_estate",
 "time": { "from": "2025-08-02T06:04:10.358Z", "to": "2025-08-02T06:34:10.358Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS" }
  ]
 },
 "panels": [
  {
   "title": "Частота запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "main_app_count_total" }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Гистограмма предсказанных цен",
   "type": "histogram",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "main_app_predictions_bucket" }
   ]
  },
  {
   "title": "Квантили цен",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(main_app_predictions_bucket[5m]))"
    },
    {
     "expr": "histogram_quantile(0.95, rate(main_app_predictions_bucket[5m]))"
    },
    {
     "expr": "histogram_quantile(0.05, rate(main_app_predictions_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Время ответа API",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m])/rate(http_request_duration_seconds_count[5m])"
    }
   ]
  }
 ]
}